title: Thomas Johansen
description: "Thomas Johansen ~> thomasjo"
url: "http://thomasjo.com"
email: "thomasjo@gmail.com"

permalink: /:categories/:year/:month/:day/:title.html

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
