name: Thomas Johansen
description: "Thomas Johansen ~> thomasjo"
url: "http://thomasjo.com"
email: "thomasjo@gmail.com"

permalink: /:categories/:year/:month/:day/:title.html

safe: false # NOTE: Will always be set to true in production.
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions:
    - smart
    - no_intra_emphasis
    - tables
    - autolink

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
